Creating Array, Slicing, Attributes 

In [2]:
#Array
import numpy as np
arr=np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [3]:
#slicing
arr=np.array([10,20,30,40])
print(arr[0:3])

[10 20 30]


In [4]:
#attributes
arr1=np.array([[10,20,30],[20,30,40],[30,40,50]])
print(np.shape(arr1))
print(np.size(arr1))
print(np.ndim(arr1))
print(arr1.dtype)

(3, 3)
9
2
int64


Mathematical operation and function on arrays

In [5]:
arr2=np.array([10,20,30,40])
arr3=np.array([30,40,50,60])
print(arr2+arr3)
print(np.add(arr2,arr3))
print(np.subtract(arr2,arr3))
print(np.multiply(arr2,arr3))
print(np.divide(arr2,arr3))
print(np.exp(arr2))
print(np.sqrt(arr3))
print(np.power(arr3,arr2))

[ 40  60  80 100]
[ 40  60  80 100]
[-20 -20 -20 -20]
[ 300  800 1500 2400]
[0.33333333 0.5        0.6        0.66666667]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
[5.47722558 6.32455532 7.07106781 7.74596669]
[    590490000000000 1152921504606846976 5878960461428293632
                   0]


Combining and Spliting in arrays

In [7]:
#concatenate
arr2=np.array([10,20,30,40])
arr3=np.array([30,40,50,60])
print(np.concatenate([arr2,arr3]))
print(np.hstack([arr2,arr3]))#for horizontal concatenate
print(np.vstack([arr2,arr3]))#for vertical concatenate

[10 20 30 40 30 40 50 60]
[10 20 30 40 30 40 50 60]
[[10 20 30 40]
 [30 40 50 60]]


In [9]:
#slitting
a=np.array([20,30,40,10,20])
print(np.array_split(a,3))

[array([20, 30]), array([40, 10]), array([20])]


Adding and Removing elements in the array

In [14]:
a=np.array([20,30,40,10,50])
print(np.append(a,90))
print(np.insert(a,1,60))
print(np.delete(a,[2]))

[20 30 40 10 50 90]
[20 60 30 40 10 50]
[20 30 10 50]


Search Sort and Filter arrays 

In [21]:
ar=np.array([7,8,9,4])
print(np.sort(ar))
s=np.where(ar==8)
print(s)
fa=[True,False,True,False]
new=ar[fa]
print(new)

[4 7 8 9]
(array([1]),)
[7 9]


Aggregate Function in numpy

In [25]:
a=np.array([10,20,30,40])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

100
10
40
4
25.0
[ 10  30  60 100]
[    10    200   6000 240000]


In [27]:
#eg of cumprod
a=[100,110,120,130]
b=[2,3,2,4]
price=np.array(a)
quantity=np.array(b)
print(price,quantity)
c=np.cumprod([price,quantity],axis=0)
print(c[1].sum())

[100 110 120 130] [2 3 2 4]
1290


Statistical function in array

In [32]:
import statistics as stats
baked_food=[200,300,400,500]
a=np.array(baked_food)
print(np.mean(a))
print(np.median(a))
#print(np.mode(a))
print(stats.mode(a))
print(np.std(a))
print(np.var(a))


350.0
350.0
200
111.80339887498948
12500.0


In [34]:
#corelation function
tobacco_consumptions=[30,40,50,60]
deaths=[100,200,300,400]
print(np.corrcoef([tobacco_consumptions,deaths]))

[[1. 1.]
 [1. 1.]]
